name: docusign-base-mininal
synopsis: Low-level bindings to the DocuSign API (only what is necessary for docusign-client)

library:
  default-extensions:
    - DeriveGeneric
    - GeneralizedNewtypeDeriving
  dependencies:
    - aeson
    - base
    - bytestring
    - data-default
    - http-media
    - lens
    - servant
    - servant-client
    - text
  exposed-modules:
    - DocuSign.Base
    - DocuSign.Base.Fields
    - DocuSign.Base.Types
    - DocuSign.Base.ContentTypes
  source-dirs:
    - src
